name: Plot Last Year Clusters Pipeline

on:
    workflow_dispatch:
    schedule:
        - cron: '0 7 1 * *'

env:
    HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

jobs:
    plot-last-year-pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11.5'
                cache: 'pip' # caching pip dependencies
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run plot pipeline
              run: python plot_last_year_clusters.py
            - name: Commit and push changes
              run: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git add docs/cluster_last_year.html
                git commit -m "Update year clusters plot"
                git push
